add doc strings to udSDK.py methods
Euclideon/udSDKPython pull request #23
Opened 2022-05-23 06:33 UTC by bwockner

2022-05-23 06:46 UTC, samsinsane requested changes

2022-05-23 06:46 UTC, samsinsane commented on src/udSDK/udSDK.py
> +  Exception class wrapping udError return values. udError value can be accessed as args[1]
Should this say `code` instead of `args[1]`?

2022-05-23 06:46 UTC, samsinsane commented on src/udSDK/udSDK.py
> +  Standar attributes as a bit field. The presence of each attribute is indicated by its bit being set
```suggestion
  Standard attributes as a bit field. The presence of each attribute is indicated by its bit being set
```

2022-05-23 06:46 UTC, samsinsane commented on src/udSDK/udSDK.py
> +  Set of udAttributes. Used when describing the contents of a udPointCLoud or a udPointBuffer
```suggestion
  Set of udAttributes. Used when describing the contents of a udPointCloud or a udPointBuffer
```

2022-05-23 06:46 UTC, samsinsane commented on src/udSDK/udSDK.py
> +    If pStruct is defined instead instantiate the object with the internal value loacted at this address
```suggestion
    If pStruct is defined instead instantiate the object with the internal value located at this address
```

2022-05-23 06:46 UTC, samsinsane commented on src/udSDK/udSDK.py
> +    Fill the point buffer with points matching the query from the pointcloud. Call repeatedly to more points matching
```suggestion
    Fill the point buffer with points matching the query from the pointcloud. Call repeatedly to get more points matching
```

I'm not certain if this is the correct change, but the sentence as-is doesn't make sense.

2022-05-23 06:46 UTC, samsinsane commented on src/udSDK/udSDK.py
> +    This loads all points matching the query into a list of point buffers of size buffersize.
```suggestion
    This loads all points matching the query into a list of point buffers of size bufferSize.
```

2022-05-24 00:37 UTC, OsiJr commented
Merging as all of Sams feedback was fixed.

2022-05-24 00:38 UTC, merged